In [2]:
import numpy as np
import sympy as sym

In [3]:
A = np.array([[5, -4, -2], [5, -5, 4],[2, 5, -4], [-5, 4, 3], [3, -4, -3]])
B = np.array([[5], [-2], [-3]])


In [4]:


def Mult_Matrices(A,B):

   filas_A, columnas_A = A.shape
   filas_B, columnas_B = B.shape
   if columnas_A != filas_B:
       print("Estas matrices no se pueden multiplicar")
   else:
       resultado = np.zeros((filas_A, columnas_B))

       for i in range(filas_A):
           for k in range(columnas_B):
               for x in range(columnas_A):
                   resultado[i][k] += A[i][x] * B[x][k]

       return resultado
        

In [5]:
R= Mult_Matrices(A,B)
R

array([[ 39.],
       [ 23.],
       [ 12.],
       [-42.],
       [ 32.]])

In [6]:
C = np.array([[0, -1, -1, 3], [5, -5, -2, 2],[1, 0, 4, 5]])
D = np.array([[0, -3], [-2, -1],[3, -3]])
T=Mult_Matrices(C,D)
T
              

Estas matrices no se pueden multiplicar


In [7]:
E = np.array([[2, -5, 5, 1], [5, 2, -7, -6],[-6, -1, 7, -4], [5, 4, 1, -5]])
F = np.array([[0, 4, -7, 1, -6], [-1, -6, -5, 1, 1], [2, -1, -6, 5, -5],[-3, -6, 6, 3, 5]])
O=Mult_Matrices(E,F)
O


array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

In [9]:
G = np.array([[2, 2], [3, 1]])
H = np.array([[1, 3], [2, 5]])
L= Mult_Matrices(G, H)
L


array([[ 6., 16.],
       [ 5., 14.]])

In [10]:
L2=Mult_Matrices(H,G)
L2

array([[11.,  5.],
       [19.,  9.]])

Como podemos ver, L es diferente de L2 lo que quiere decir que G*H es diferente a H*G, podemos concluir entonces que la multiplicación de matrices no es conmutativa. 